In [4]:
!pip install country_converter

Collecting country_converter
  Downloading country_converter-1.3.2-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: pandas>=1.0 in /usr/local/lib/python3.12/dist-packages (from country_converter) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0->country_converter) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0->country_converter) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0->country_converter) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0->country_converter) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0->country_converter) (1.17.0)
Downloading country_converter-1.3.2-py3-none-any.whl (47 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.5/47.5 kB 4.3 MB/s eta 0:00:00
Installing collected packages: country_converter
Successfully installed country_converter-1.3.2

In [5]:
import pandas as pd
import country_converter as coco
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
whr = pd.read_excel('/content/drive/MyDrive/Jedha-Fullstack/FS_ProjetFinal_Room3/WHR25_Data_Figure_2.1v3.xlsx')
whr.head()

,Year,Rank,Country name,Life evaluation (3-year average),Lower whisker,Upper whisker,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,2024,147,Afghanistan,1.364,1.301,1.427,0.649,0.0,0.155,0.0,0.075,0.135,0.348
1,2023,143,Afghanistan,1.721,1.667,1.775,0.628,0.0,0.242,0.0,0.091,0.088,0.672
2,2022,137,Afghanistan,1.859,1.795,1.923,0.645,0.0,0.087,0.0,0.093,0.059,0.976
3,2021,146,Afghanistan,2.404,2.339,2.469,0.758,0.0,0.289,0.0,0.089,0.005,1.263
4,2020,150,Afghanistan,2.523,2.449,2.596,0.370,0.0,0.126,0.0,0.122,0.010,1.895

In [7]:
wb = pd.read_csv('/content/drive/MyDrive/Jedha-Fullstack/FS_ProjetFinal_Room3/world_bank_data_2025.csv')
wb.head()

,country_name,country_id,year,Inflation (CPI %),GDP (Current USD),GDP per Capita (Current USD),Unemployment Rate (%),"Interest Rate (Real, %)","Inflation (GDP Deflator, %)",GDP Growth (% Annual),Current Account Balance (% GDP),Government Expense (% of GDP),Government Revenue (% of GDP),Tax Revenue (% of GDP),Gross National Income (USD),Public Debt (% of GDP)
0,Aruba,aw,2010,2.078141,2.453597e+09,24093.140151,NaN,11.666131,-1.223407,-2.733457,-18.752537,NaN,NaN,NaN,2.313385e+09,NaN
1,Aruba,aw,2011,4.316297,2.637859e+09,25712.384302,NaN,4.801974,4.005674,3.369237,-9.877656,NaN,NaN,NaN,2.391841e+09,NaN
2,Aruba,aw,2012,0.627472,2.615208e+09,25119.665545,NaN,8.200875,0.184033,-1.040800,3.473451,NaN,NaN,NaN,2.499118e+09,NaN
3,Aruba,aw,2013,-2.372065,2.727850e+09,25813.576727,NaN,10.709709,-1.995948,6.431483,-11.813206,NaN,NaN,NaN,2.563517e+09,NaN
4,Aruba,aw,2014,0.421441,2.790850e+09,26129.839062,NaN,3.213869,3.958897,-1.586575,-4.658577,NaN,NaN,NaN,2.688102e+09,NaN

In [8]:
print(whr.columns)
print(wb.columns)

Index(['Year', 'Rank', 'Country name', 'Life evaluation (3-year average)',
       'Lower whisker', 'Upper whisker', 'Explained by: Log GDP per capita',
       'Explained by: Social support', 'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')
Index(['country_name', 'country_id', 'year', 'Inflation (CPI %)',
       'GDP (Current USD)', 'GDP per Capita (Current USD)',
       'Unemployment Rate (%)', 'Interest Rate (Real, %)',
       'Inflation (GDP Deflator, %)', 'GDP Growth (% Annual)',
       'Current Account Balance (% GDP)', 'Government Expense (% of GDP)',
       'Government Revenue (% of GDP)', 'Tax Revenue (% of GDP)',
       'Gross National Income (USD)', 'Public Debt (% of GDP)'],
      dtype='object')

In [9]:
# on met les colonnes des 2 datasets en snake_case pour simplifier la suite du process

def clean_columns(df):
    df.columns = (
        df.columns
        .str.strip()                 # enlève espaces début/fin
        .str.lower()                 # minuscule
        .str.replace(' ', '_')       # espace → underscore
        .str.replace('-', '_')       # tiret → underscore
        .str.replace(r'[^\w]', '', regex=True)  # enlève caractères spéciaux
    )
    return df

whr = clean_columns(whr)
wb  = clean_columns(wb)

In [10]:
print(whr.columns)
print(wb.columns)

Index(['year', 'rank', 'country_name', 'life_evaluation_3_year_average',
       'lower_whisker', 'upper_whisker', 'explained_by_log_gdp_per_capita',
       'explained_by_social_support', 'explained_by_healthy_life_expectancy',
       'explained_by_freedom_to_make_life_choices', 'explained_by_generosity',
       'explained_by_perceptions_of_corruption', 'dystopia__residual'],
      dtype='object')
Index(['country_name', 'country_id', 'year', 'inflation_cpi_',
       'gdp_current_usd', 'gdp_per_capita_current_usd', 'unemployment_rate_',
       'interest_rate_real_', 'inflation_gdp_deflator_', 'gdp_growth__annual',
       'current_account_balance__gdp', 'government_expense__of_gdp',
       'government_revenue__of_gdp', 'tax_revenue__of_gdp',
       'gross_national_income_usd', 'public_debt__of_gdp'],
      dtype='object')

In [11]:
# On crée les colonnes iso 3

whr['iso_3'] = coco.convert(names=whr['country_name'], to='ISO3')
wb['iso_3'] = coco.convert(names=wb['country_name'], to='ISO3')

# Pas de conversion possible pour Channel Island !!! (ni Channel N°5)

WARNING:country_converter.country_converter:Channel Islands not found in regex
WARNING:country_converter.country_converter:Channel Islands not found in regex
WARNING:country_converter.country_converter:Channel Islands not found in regex
WARNING:country_converter.country_converter:Channel Islands not found in regex
WARNING:country_converter.country_converter:Channel Islands not found in regex
WARNING:country_converter.country_converter:Channel Islands not found in regex
WARNING:country_converter.country_converter:Channel Islands not found in regex
WARNING:country_converter.country_converter:Channel Islands not found in regex
WARNING:country_converter.country_converter:Channel Islands not found in regex
WARNING:country_converter.country_converter:Channel Islands not found in regex
WARNING:country_converter.country_converter:Channel Islands not found in regex
WARNING:country_converter.country_converter:Channel Islands not found in regex
WARNING:country_converter.country_converter:Channel Islands not found in regex
WARNING:country_converter.country_converter:Channel Islands not found in regex
WARNING:country_converter.country_converter:Channel Islands not found in regex
WARNING:country_converter.country_converter:Channel Islands not found in regex

In [12]:
# on supprime les colonnes Channel Island de "wb" car elles ne se trouveny pas dans le dataset "whr"
# Elles sont donc inutiles

wb = wb[wb['country_name'] != 'Channel Islands'].copy()

In [13]:
wb['iso3'] = coco.convert(names=wb['country_name'], to='ISO3')

In [14]:
wb.head()

,country_name,country_id,year,inflation_cpi_,gdp_current_usd,gdp_per_capita_current_usd,unemployment_rate_,interest_rate_real_,inflation_gdp_deflator_,gdp_growth__annual,current_account_balance__gdp,government_expense__of_gdp,government_revenue__of_gdp,tax_revenue__of_gdp,gross_national_income_usd,public_debt__of_gdp,iso_3,iso3
0,Aruba,aw,2010,2.078141,2.453597e+09,24093.140151,NaN,11.666131,-1.223407,-2.733457,-18.752537,NaN,NaN,NaN,2.313385e+09,NaN,ABW,ABW
1,Aruba,aw,2011,4.316297,2.637859e+09,25712.384302,NaN,4.801974,4.005674,3.369237,-9.877656,NaN,NaN,NaN,2.391841e+09,NaN,ABW,ABW
2,Aruba,aw,2012,0.627472,2.615208e+09,25119.665545,NaN,8.200875,0.184033,-1.040800,3.473451,NaN,NaN,NaN,2.499118e+09,NaN,ABW,ABW
3,Aruba,aw,2013,-2.372065,2.727850e+09,25813.576727,NaN,10.709709,-1.995948,6.431483,-11.813206,NaN,NaN,NaN,2.563517e+09,NaN,ABW,ABW
4,Aruba,aw,2014,0.421441,2.790850e+09,26129.839062,NaN,3.213869,3.958897,-1.586575,-4.658577,NaN,NaN,NaN,2.688102e+09,NaN,ABW,ABW

In [15]:
whr.head()

,year,rank,country_name,life_evaluation_3_year_average,lower_whisker,upper_whisker,explained_by_log_gdp_per_capita,explained_by_social_support,explained_by_healthy_life_expectancy,explained_by_freedom_to_make_life_choices,explained_by_generosity,explained_by_perceptions_of_corruption,dystopia__residual,iso_3
0,2024,147,Afghanistan,1.364,1.301,1.427,0.649,0.0,0.155,0.0,0.075,0.135,0.348,AFG
1,2023,143,Afghanistan,1.721,1.667,1.775,0.628,0.0,0.242,0.0,0.091,0.088,0.672,AFG
2,2022,137,Afghanistan,1.859,1.795,1.923,0.645,0.0,0.087,0.0,0.093,0.059,0.976,AFG
3,2021,146,Afghanistan,2.404,2.339,2.469,0.758,0.0,0.289,0.0,0.089,0.005,1.263,AFG
4,2020,150,Afghanistan,2.523,2.449,2.596,0.370,0.0,0.126,0.0,0.122,0.010,1.895,AFG

In [16]:
# création d'une colonne iso3 + year pour chaque datasets. On les utilisera comme primary key

whr['year'] = whr['year'].astype(str)
whr['iso3_year'] = whr['iso_3'] + whr['year']

wb['year'] = wb['year'].astype(str)
wb['iso3_year'] = wb['iso_3'] + wb['year']

In [17]:
# checks que les clés sont vraiment uniques pour le join (afin d'éviter les doublons au join)

print(f"nombre de duplications de valeur pour whr = {whr.duplicated('iso3_year').sum()}")
print(f"nombre de duplications de valeur pour wb = {wb.duplicated('iso3_year').sum()}")

nombre de duplications de valeur pour whr = 10
nombre de duplications de valeur pour wb = 0

In [18]:
# voir les lignes dupliquées

whr[whr.duplicated('iso3_year', keep=False)].sort_values('iso3_year')

,year,rank,country_name,life_evaluation_3_year_average,lower_whisker,upper_whisker,explained_by_log_gdp_per_capita,explained_by_social_support,explained_by_healthy_life_expectancy,explained_by_freedom_to_make_life_choices,explained_by_generosity,explained_by_perceptions_of_corruption,dystopia__residual,iso_3,iso3_year
440,2012,34,Cyprus,6.4660,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CYP,CYP2012
1308,2012,69,North Cyprus,5.4630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CYP,CYP2012
439,2014,67,Cyprus,5.6890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CYP,CYP2014
1307,2014,66,North Cyprus,5.6950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CYP,CYP2014
438,2015,69,Cyprus,5.5460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CYP,CYP2015
1306,2015,62,North Cyprus,5.7710,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CYP,CYP2015
437,2016,65,Cyprus,5.6210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CYP,CYP2016
1305,2016,61,North Cyprus,5.8100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CYP,CYP2016
436,2017,61,Cyprus,5.7620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CYP,CYP2017
1304,2017,58,North Cyprus,5.8350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CYP,CYP2017
1303,2018,64,North Cyprus,5.7180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CYP,CYP2018
435,2018,49,Cyprus,6.0460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CYP,CYP2018
434,2019,45,Cyprus,6.1590,6.059812,6.258188,1.212799,1.149171,1.026125,0.459386,0.227932,0.051207,2.032335,CYP,CYP2019
1302,2019,76,North Cyprus,5.5355,5.435467,5.635533,1.212799,1.183089,1.026125,0.477886,0.199160,0.199803,1.236688,CYP,CYP2019
433,2020,40,Cyprus,6.2230,6.128000,6.319000,1.377000,0.765000,0.801000,0.464000,0.178000,0.061000,2.578000,CYP,CYP2020
1301,2020,75,North Cyprus,5.5360,5.435000,5.636000,1.377000,0.806000,0.801000,0.503000,0.196000,0.200000,1.653000,CYP,CYP2020
432,2021,41,Cyprus,6.2210,6.122000,6.320000,1.815000,0.909000,0.819000,0.448000,0.123000,0.062000,2.044000,CYP,CYP2021
1300,2021,79,North Cyprus,5.4670,5.325000,5.609000,1.815000,0.888000,0.819000,0.523000,0.130000,0.213000,1.078000,CYP,CYP2021
1595,2015,76,Somalia,5.4400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SOM,SOM2015
1596,2015,97,Somaliland Region,5.0570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SOM,SOM2015

In [24]:
# on va vérifier si ces clés (de whr) existe dans wb autrement on les supprimera

whr[~whr['iso3_year'].isin(wb['iso3_year'])]['iso3_year'].unique()

# on voit que Taiwan ne se trouve pas dans WB
# on peut aussi déduire que "Cyprus" et "Somalia" existent mais pas "North Cyprus" ni "Somaliland Region"
# On peut donc supprimer ces lignes

array(['TWN2024', 'TWN2023', 'TWN2022', 'TWN2021', 'TWN2020', 'TWN2019',
       'TWN2018', 'TWN2017', 'TWN2016', 'TWN2015', 'TWN2014', 'TWN2012',
       'TWN2011'], dtype=object)

In [20]:
# suppresion des lignes 'North Cyprus' et 'Somaliland Region'

whr = whr[
    (whr['country_name'] != 'North Cyprus') &
    (whr['country_name'] != 'Somaliland Region')
].copy()

In [21]:
# Ultime petit check


print(f"nombre de duplications de valeur pour whr = {whr.duplicated('iso3_year').sum()}")
print(f"nombre de duplications de valeur pour wb = {wb.duplicated('iso3_year').sum()}")

nombre de duplications de valeur pour whr = 0
nombre de duplications de valeur pour wb = 0

In [22]:
# au final combien de clés communes avons nous et quelle pourcentage de perte

same_keys = len(set(whr['iso3_year']) & set(wb['iso3_year']))
print(f"nombre de clés communes = {same_keys}")

len_keys_whr = whr['iso3_year'].nunique()
print(f"nombre de clés WHR = {len_keys_whr}")

len_keys_wb = wb['iso3_year'].nunique()
print(f"nombre de clés WB = {len_keys_wb}")

nombre de clés communes = 1943
nombre de clés WHR = 1956
nombre de clés WB = 3456

In [23]:
# pourcentage de perte dans chaque dataset après jointure

print(f"pourcentage de perte pour WHR = {round(100 - (same_keys / len_keys_whr * 100), 2)}%")
print(f"pourcentage de perte pour WB = {round(100 - (same_keys / len_keys_wb * 100), 2)}%")

pourcentage de perte pour WHR = 0.66%
pourcentage de perte pour WB = 43.78%

In [25]:
whr[whr['country_name'] == 'Syria']

,year,rank,country_name,life_evaluation_3_year_average,lower_whisker,upper_whisker,explained_by_log_gdp_per_capita,explained_by_social_support,explained_by_healthy_life_expectancy,explained_by_freedom_to_make_life_choices,explained_by_generosity,explained_by_perceptions_of_corruption,dystopia__residual,iso_3,iso3_year
1697,2018,149,Syria,3.462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYR,SYR2018
1698,2017,150,Syria,3.462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYR,SYR2017
1699,2016,152,Syria,3.462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYR,SYR2016
1700,2015,156,Syria,3.069,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYR,SYR2015
1701,2014,156,Syria,3.006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYR,SYR2014
1702,2012,148,Syria,3.892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYR,SYR2012
1703,2011,107,Syria,4.735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYR,SYR2011

In [27]:
wb[wb['country_name'] == 'Syria']

Empty DataFrame
Columns: [country_name, country_id, year, inflation_cpi_, gdp_current_usd, gdp_per_capita_current_usd, unemployment_rate_, interest_rate_real_, inflation_gdp_deflator_, gdp_growth__annual, current_account_balance__gdp, government_expense__of_gdp, government_revenue__of_gdp, tax_revenue__of_gdp, gross_national_income_usd, public_debt__of_gdp, iso_3, iso3, iso3_year]
Index: []

In [31]:
# merge par "iso3_year" comme primary key

df_final = pd.merge(
    whr,
    wb,
    on='iso3_year',
    how='inner'   # garde seulement les clés communes
)

In [32]:
df_final.shape

(1943, 33)

In [33]:
df_final.head()

,year_x,rank,country_name_x,life_evaluation_3_year_average,lower_whisker,upper_whisker,explained_by_log_gdp_per_capita,explained_by_social_support,explained_by_healthy_life_expectancy,explained_by_freedom_to_make_life_choices,...,inflation_gdp_deflator_,gdp_growth__annual,current_account_balance__gdp,government_expense__of_gdp,government_revenue__of_gdp,tax_revenue__of_gdp,gross_national_income_usd,public_debt__of_gdp,iso_3_y,iso3
0,2024,147,Afghanistan,1.364,1.301,1.427,0.649,0.0,0.155,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AFG,AFG
1,2023,143,Afghanistan,1.721,1.667,1.775,0.628,0.0,0.242,0.0,...,2.961654,2.710887,NaN,NaN,NaN,NaN,1.731538e+10,NaN,AFG,AFG
2,2022,137,Afghanistan,1.859,1.795,1.923,0.645,0.0,0.087,0.0,...,9.406239,-6.240172,NaN,NaN,NaN,NaN,1.454030e+10,NaN,AFG,AFG
3,2021,146,Afghanistan,2.404,2.339,2.469,0.758,0.0,0.289,0.0,...,2.838996,-20.738839,NaN,NaN,NaN,NaN,1.434609e+10,NaN,AFG,AFG
4,2020,150,Afghanistan,2.523,2.449,2.596,0.370,0.0,0.126,0.0,...,6.962946,-2.351101,-15.718303,NaN,NaN,NaN,2.010516e+10,NaN,AFG,AFG

In [35]:
# exporter le dataset final en csv

df_final.to_csv('/content/drive/MyDrive/Jedha-Fullstack/FS_ProjetFinal_Room3/df_final.csv')