In [2]:
import pandas as pd

df = pd.read_csv("../data/processed/df_final.csv")

In [3]:
df.shape

(1943, 34)

In [4]:
df.isna().sum()

Unnamed: 0                                      0
year_x                                          0
rank                                            0
country_name_x                                  0
life_evaluation_3_year_average                  0
lower_whisker                                1077
upper_whisker                                1077
explained_by_log_gdp_per_capita              1080
explained_by_social_support                  1080
explained_by_healthy_life_expectancy         1082
explained_by_freedom_to_make_life_choices    1081
explained_by_generosity                      1080
explained_by_perceptions_of_corruption       1081
dystopia__residual                           1084
iso_3_x                                         0
iso3_year                                       0
country_name_y                                  0
country_id                                      0
year_y                                          0
inflation_cpi_                                113
gdp_current_usd                               164
gdp_per_capita_current_usd                    160
unemployment_rate_                             19
interest_rate_real_                           865
inflation_gdp_deflator_                       166
gdp_growth__annual                            166
current_account_balance__gdp                  257
government_expense__of_gdp                    624
government_revenue__of_gdp                    619
tax_revenue__of_gdp                           617
gross_national_income_usd                     164
public_debt__of_gdp                          1320
iso_3_y                                         0
iso3                                            0
dtype: int64

In [5]:
df.head()

,Unnamed: 0,year_x,rank,country_name_x,life_evaluation_3_year_average,lower_whisker,upper_whisker,explained_by_log_gdp_per_capita,explained_by_social_support,explained_by_healthy_life_expectancy,...,inflation_gdp_deflator_,gdp_growth__annual,current_account_balance__gdp,government_expense__of_gdp,government_revenue__of_gdp,tax_revenue__of_gdp,gross_national_income_usd,public_debt__of_gdp,iso_3_y,iso3
0,0,2024,147,Afghanistan,1.364,1.301,1.427,0.649,0.0,0.155,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AFG,AFG
1,1,2023,143,Afghanistan,1.721,1.667,1.775,0.628,0.0,0.242,...,2.961654,2.710887,NaN,NaN,NaN,NaN,1.731538e+10,NaN,AFG,AFG
2,2,2022,137,Afghanistan,1.859,1.795,1.923,0.645,0.0,0.087,...,9.406239,-6.240172,NaN,NaN,NaN,NaN,1.454030e+10,NaN,AFG,AFG
3,3,2021,146,Afghanistan,2.404,2.339,2.469,0.758,0.0,0.289,...,2.838996,-20.738839,NaN,NaN,NaN,NaN,1.434609e+10,NaN,AFG,AFG
4,4,2020,150,Afghanistan,2.523,2.449,2.596,0.370,0.0,0.126,...,6.962946,-2.351101,-15.718303,NaN,NaN,NaN,2.010516e+10,NaN,AFG,AFG

In [6]:
df.columns

Index(['Unnamed: 0', 'year_x', 'rank', 'country_name_x',
       'life_evaluation_3_year_average', 'lower_whisker', 'upper_whisker',
       'explained_by_log_gdp_per_capita', 'explained_by_social_support',
       'explained_by_healthy_life_expectancy',
       'explained_by_freedom_to_make_life_choices', 'explained_by_generosity',
       'explained_by_perceptions_of_corruption', 'dystopia__residual',
       'iso_3_x', 'iso3_year', 'country_name_y', 'country_id', 'year_y',
       'inflation_cpi_', 'gdp_current_usd', 'gdp_per_capita_current_usd',
       'unemployment_rate_', 'interest_rate_real_', 'inflation_gdp_deflator_',
       'gdp_growth__annual', 'current_account_balance__gdp',
       'government_expense__of_gdp', 'government_revenue__of_gdp',
       'tax_revenue__of_gdp', 'gross_national_income_usd',
       'public_debt__of_gdp', 'iso_3_y', 'iso3'],
      dtype='object')

In [7]:
df = df.drop(["Unnamed: 0", "rank", "iso_3_x", "iso_3_y", "country_name_y", "country_id", "year_y"], axis=1)

In [8]:
df.columns

Index(['year_x', 'country_name_x', 'life_evaluation_3_year_average',
       'lower_whisker', 'upper_whisker', 'explained_by_log_gdp_per_capita',
       'explained_by_social_support', 'explained_by_healthy_life_expectancy',
       'explained_by_freedom_to_make_life_choices', 'explained_by_generosity',
       'explained_by_perceptions_of_corruption', 'dystopia__residual',
       'iso3_year', 'inflation_cpi_', 'gdp_current_usd',
       'gdp_per_capita_current_usd', 'unemployment_rate_',
       'interest_rate_real_', 'inflation_gdp_deflator_', 'gdp_growth__annual',
       'current_account_balance__gdp', 'government_expense__of_gdp',
       'government_revenue__of_gdp', 'tax_revenue__of_gdp',
       'gross_national_income_usd', 'public_debt__of_gdp', 'iso3'],
      dtype='object')

In [9]:
df.shape

(1943, 27)

In [10]:
df.columns = ['year', 'country_name', 'life_evaluation_3_year_average',
       'lower_whisker', 'upper_whisker', 'explained_by_log_gdp_per_capita',
       'explained_by_social_support', 'explained_by_healthy_life_expectancy',
       'explained_by_freedom_to_make_life_choices', 'explained_by_generosity',
       'explained_by_perceptions_of_corruption', 'dystopia_residual',
       'key_iso3_year', 'inflation_cpi', 'gdp_current_usd',
       'gdp_per_capita_current_usd', 'unemployment_rate_',
       'interest_rate_real', 'inflation_gdp_deflator', 'gdp_growth_annual',
       'current_account_balance_gdp', 'government_expense_of_gdp',
       'government_revenue_of_gdp', 'tax_revenue_of_gdp',
       'gross_national_income_usd', 'public_debt_of_gdp', 'country_code']

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1943 entries, 0 to 1942
Data columns (total 27 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   year                                       1943 non-null   int64
 1   country_name                               1943 non-null   object
 2   life_evaluation_3_year_average             1943 non-null   float64
 3   lower_whisker                              866 non-null    float64
 4   upper_whisker                              866 non-null    float64
 5   explained_by_log_gdp_per_capita            863 non-null    float64
 6   explained_by_social_support                863 non-null    float64
 7   explained_by_healthy_life_expectancy       861 non-null    float64
 8   explained_by_freedom_to_make_life_choices  862 non-null    float64
 9   explained_by_generosity                    863 non-null    float64
 10  explained_by_perceptions_of_corruption     862 non-null    float64
 11  dystopia_residual                          859 non-null    float64
 12  key_iso3_year                              1943 non-null   object
 13  inflation_cpi                              1830 non-null   float64
 14  gdp_current_usd                            1779 non-null   float64
 15  gdp_per_capita_current_usd                 1783 non-null   float64
 16  unemployment_rate_                         1924 non-null   float64
 17  interest_rate_real                         1078 non-null   float64
 18  inflation_gdp_deflator                     1777 non-null   float64
 19  gdp_growth_annual                          1777 non-null   float64
 20  current_account_balance_gdp                1686 non-null   float64
 21  government_expense_of_gdp                  1319 non-null   float64
 22  government_revenue_of_gdp                  1324 non-null   float64
 23  tax_revenue_of_gdp                         1326 non-null   float64
 24  gross_national_income_usd                  1779 non-null   float64
 25  public_debt_of_gdp                         623 non-null    float64
 26  country_code                               1943 non-null   object
dtypes: float64(23), int64(1), object(3)
memory usage: 410.0+ KB

In [12]:
df = df.astype({col: "string" for col in df.select_dtypes(include="object").columns})

In [13]:
df = df.round(3)

In [14]:
df.dtypes

year                                                  int64
country_name                                 string[python]
life_evaluation_3_year_average                      float64
lower_whisker                                       float64
upper_whisker                                       float64
explained_by_log_gdp_per_capita                     float64
explained_by_social_support                         float64
explained_by_healthy_life_expectancy                float64
explained_by_freedom_to_make_life_choices           float64
explained_by_generosity                             float64
explained_by_perceptions_of_corruption              float64
dystopia_residual                                   float64
key_iso3_year                                string[python]
inflation_cpi                                       float64
gdp_current_usd                                     float64
gdp_per_capita_current_usd                          float64
unemployment_rate_                                  float64
interest_rate_real                                  float64
inflation_gdp_deflator                              float64
gdp_growth_annual                                   float64
current_account_balance_gdp                         float64
government_expense_of_gdp                           float64
government_revenue_of_gdp                           float64
tax_revenue_of_gdp                                  float64
gross_national_income_usd                           float64
public_debt_of_gdp                                  float64
country_code                                 string[python]
dtype: object

In [15]:
df.head(50)

,year,country_name,life_evaluation_3_year_average,lower_whisker,upper_whisker,explained_by_log_gdp_per_capita,explained_by_social_support,explained_by_healthy_life_expectancy,explained_by_freedom_to_make_life_choices,explained_by_generosity,...,interest_rate_real,inflation_gdp_deflator,gdp_growth_annual,current_account_balance_gdp,government_expense_of_gdp,government_revenue_of_gdp,tax_revenue_of_gdp,gross_national_income_usd,public_debt_of_gdp,country_code
0,2024,Afghanistan,1.364,1.301,1.427,0.649,0.000,0.155,0.000,0.075,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AFG
1,2023,Afghanistan,1.721,1.667,1.775,0.628,0.000,0.242,0.000,0.091,...,NaN,2.962,2.711,NaN,NaN,NaN,NaN,1.731538e+10,NaN,AFG
2,2022,Afghanistan,1.859,1.795,1.923,0.645,0.000,0.087,0.000,0.093,...,NaN,9.406,-6.240,NaN,NaN,NaN,NaN,1.454030e+10,NaN,AFG
3,2021,Afghanistan,2.404,2.339,2.469,0.758,0.000,0.289,0.000,0.089,...,NaN,2.839,-20.739,NaN,NaN,NaN,NaN,1.434609e+10,NaN,AFG
4,2020,Afghanistan,2.523,2.449,2.596,0.370,0.000,0.126,0.000,0.122,...,NaN,6.963,-2.351,-15.718,NaN,NaN,NaN,2.010516e+10,NaN,AFG
5,2019,Afghanistan,2.567,2.506,2.628,0.301,0.356,0.266,0.000,0.135,...,NaN,6.521,3.912,-20.170,NaN,NaN,NaN,1.908066e+10,NaN,AFG
6,2018,Afghanistan,3.203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.071,1.189,-21.585,NaN,NaN,NaN,1.829451e+10,NaN,AFG
7,2017,Afghanistan,3.632,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.141,2.404,2.647,-18.956,39.220,13.039,9.898,1.896177e+10,NaN,AFG
8,2016,Afghanistan,3.794,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.584,-2.198,2.260,-14.950,43.923,12.678,9.503,1.835048e+10,NaN,AFG
9,2015,Afghanistan,3.360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.253,2.448,1.451,-21.913,37.023,10.131,7.585,1.924950e+10,NaN,AFG
10,2014,Afghanistan,3.575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.352,0.567,2.725,-15.772,44.589,8.614,6.882,2.055967e+10,NaN,AFG
11,2012,Afghanistan,4.040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.174,7.302,12.752,-25.871,42.329,10.201,7.708,1.996126e+10,NaN,AFG
12,2011,Afghanistan,4.258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.242,16.593,0.426,-12.620,59.485,11.510,8.917,1.778151e+10,NaN,AFG
13,2024,Albania,5.411,5.284,5.539,1.371,1.122,0.696,0.841,0.103,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ALB
14,2023,Albania,5.304,5.168,5.440,1.438,0.924,0.638,0.690,0.138,...,0.269,6.066,3.937,-1.196,25.376,24.697,17.760,2.324648e+10,NaN,ALB
15,2022,Albania,5.277,5.148,5.406,1.449,0.951,0.480,0.549,0.133,...,-3.054,9.862,4.827,-5.872,27.003,24.732,18.061,1.868602e+10,NaN,ALB
16,2021,Albania,5.199,5.076,5.321,1.439,0.646,0.719,0.511,0.138,...,2.491,3.444,8.970,-7.596,24.398,25.047,18.096,1.778084e+10,81.920,ALB
17,2020,Albania,5.117,5.001,5.234,1.008,0.529,0.646,0.491,0.168,...,6.077,0.041,-3.314,-8.625,24.605,23.701,16.896,1.499123e+10,83.454,ALB
18,2019,Albania,4.883,4.773,4.993,0.907,0.830,0.846,0.462,0.171,...,5.223,1.001,2.063,-7.821,22.878,24.846,17.931,1.538352e+10,74.808,ALB
19,2018,Albania,4.719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.881,2.967,4.019,-6.608,22.929,25.108,18.277,1.536107e+10,63.634,ALB
20,2017,Albania,4.586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.701,1.451,3.803,-7.544,23.868,25.733,18.887,1.305152e+10,75.889,ALB
21,2016,Albania,4.644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.414,-0.633,3.315,-7.591,23.957,24.279,17.590,1.205383e+10,80.736,ALB
22,2015,Albania,4.655,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.272,0.564,2.219,-8.605,24.446,24.738,18.516,1.152181e+10,79.864,ALB
23,2014,Albania,4.959,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.325,1.550,1.774,-10.775,24.383,24.525,18.302,1.334942e+10,73.320,ALB
24,2012,Albania,5.550,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.736,1.043,1.417,-10.200,23.008,23.051,17.483,1.222807e+10,63.669,ALB
25,2011,Albania,5.134,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.888,2.315,2.545,-12.933,23.011,23.900,18.022,1.289410e+10,69.638,ALB
26,2024,Algeria,5.571,5.469,5.674,1.315,1.363,0.782,0.522,0.057,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DZA
27,2023,Algeria,5.364,5.251,5.476,1.324,1.191,0.568,0.247,0.091,...,7.085,0.855,4.100,2.568,NaN,NaN,NaN,2.440411e+11,NaN,DZA
28,2022,Algeria,5.329,5.207,5.451,1.353,1.298,0.409,0.252,0.073,...,-12.160,22.951,3.600,8.612,NaN,NaN,NaN,2.203784e+11,NaN,DZA
29,2021,Algeria,5.122,5.030,5.215,1.363,0.970,0.643,0.146,0.106,...,-6.842,15.933,3.800,-2.423,NaN,NaN,NaN,1.825885e+11,NaN,DZA
30,2020,Algeria,4.887,4.783,4.991,0.946,0.765,0.552,0.119,0.144,...,13.340,-4.711,-5.000,-11.031,NaN,NaN,NaN,1.621371e+11,NaN,DZA
31,2019,Algeria,5.005,4.918,5.092,0.944,1.143,0.745,0.084,0.119,...,7.055,0.883,0.900,-8.764,NaN,NaN,NaN,1.895486e+11,NaN,DZA
32,2018,Algeria,5.211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.729,6.165,1.400,-8.689,NaN,NaN,NaN,1.903905e+11,NaN,DZA
33,2017,Algeria,5.295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.918,4.938,1.500,-11.622,NaN,NaN,NaN,1.876822e+11,NaN,DZA
34,2016,Algeria,5.872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.083,0.857,3.900,-14.496,NaN,NaN,NaN,1.795943e+11,NaN,DZA
35,2015,Algeria,6.355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.668,-4.987,3.200,-14.421,NaN,NaN,NaN,1.836494e+11,NaN,DZA
36,2014,Algeria,5.605,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.456,1.450,4.100,-3.877,NaN,NaN,NaN,2.344613e+11,NaN,DZA
37,2012,Algeria,5.422,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.002,8.002,2.400,5.324,NaN,NaN,NaN,2.249641e+11,NaN,DZA
38,2011,Algeria,5.368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-7.620,16.909,3.000,8.095,NaN,NaN,NaN,2.165894e+11,NaN,DZA
39,2017,Angola,3.795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-5.553,22.615,-0.147,-0.859,16.671,16.361,9.224,6.916123e+10,NaN,AGO
40,2016,Angola,3.795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-4.922,21.774,-2.580,-5.847,17.512,15.721,9.733,5.001006e+10,NaN,AGO
41,2015,Angola,3.866,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.144,-3.518,0.944,-11.352,20.819,18.777,11.002,8.589538e+10,NaN,AGO
42,2014,Angola,4.033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.381,3.561,4.823,-2.756,27.967,30.885,13.543,1.277088e+11,NaN,AGO
43,2012,Angola,5.589,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.765,7.256,8.542,10.809,23.450,36.225,14.823,1.176312e+11,NaN,AGO
44,2011,Angola,4.178,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-9.876,31.771,3.472,11.705,26.671,44.592,16.103,1.020924e+11,NaN,AGO
45,2024,Argentina,6.397,6.302,6.492,1.504,1.622,0.579,0.824,0.048,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARG
46,2023,Argentina,6.188,6.070,6.306,1.562,1.381,0.585,0.681,0.087,...,-16.771,135.369,-1.611,-3.244,NaN,NaN,NaN,6.327299e+11,NaN,ARG
47,2022,Argentina,6.024,5.900,6.147,1.590,1.388,0.427,0.587,0.088,...,-10.288,69.876,5.270,-0.641,21.907,17.927,11.123,6.211652e+11,NaN,ARG
48,2021,Argentina,5.967,5.844,6.090,1.592,1.102,0.662,0.555,0.081,...,-11.862,53.802,10.442,1.362,22.897,18.076,11.500,4.768023e+11,NaN,ARG
49,2020,Argentina,5.929,5.819,6.040,1.162,0.980,0.646,0.544,0.069,...,-7.635,40.083,-9.900,0.697,25.841,17.479,10.866,3.753441e+11,NaN,ARG

In [16]:
nulls_by_country = (
    df.isna()
      .groupby(df["country_name"])
      .sum()
)

nulls_by_country

,year,country_name,life_evaluation_3_year_average,lower_whisker,upper_whisker,explained_by_log_gdp_per_capita,explained_by_social_support,explained_by_healthy_life_expectancy,explained_by_freedom_to_make_life_choices,explained_by_generosity,...,interest_rate_real,inflation_gdp_deflator,gdp_growth_annual,current_account_balance_gdp,government_expense_of_gdp,government_revenue_of_gdp,tax_revenue_of_gdp,gross_national_income_usd,public_debt_of_gdp,country_code
country_name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0,0,0,7,7,7,7,7,7,7,...,7,1,1,4,7,7,7,1,13,0
Albania,0,0,0,7,7,7,7,7,7,7,...,1,1,1,1,1,1,1,1,3,0
Algeria,0,0,0,7,7,7,7,7,7,7,...,1,1,1,1,13,13,13,1,13,0
Angola,0,0,0,6,6,6,6,6,6,6,...,0,0,0,0,0,0,0,0,6,0
Argentina,0,0,0,7,7,7,7,7,7,7,...,1,1,1,1,4,2,2,1,13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,0,0,0,7,7,7,7,7,7,7,...,10,10,10,10,13,13,13,10,13,0
Viet Nam,0,0,0,7,7,7,7,7,7,7,...,1,1,1,1,13,13,13,1,13,0
Yemen,0,0,0,7,7,7,7,7,7,7,...,10,5,5,7,12,12,12,5,12,0
Zambia,0,0,0,7,7,7,7,7,7,7,...,4,1,1,1,3,3,3,1,3,0
Zimbabwe,0,0,0,7,7,7,7,7,7,7,...,2,1,1,1,7,7,7,1,13,0

In [17]:
nulls_by_year = (
    df.isna()
      .groupby(df["year"])
      .sum()
)

nulls_by_year

,year,country_name,life_evaluation_3_year_average,lower_whisker,upper_whisker,explained_by_log_gdp_per_capita,explained_by_social_support,explained_by_healthy_life_expectancy,explained_by_freedom_to_make_life_choices,explained_by_generosity,...,interest_rate_real,inflation_gdp_deflator,gdp_growth_annual,current_account_balance_gdp,government_expense_of_gdp,government_revenue_of_gdp,tax_revenue_of_gdp,gross_national_income_usd,public_debt_of_gdp,country_code
year,,,,,,,,,,,,,,,,,,,,,
2011,0,0,0,154,154,154,154,154,154,154,...,48,1,1,9,45,43,42,0,100,0
2012,0,0,0,153,153,153,153,153,153,153,...,46,1,1,6,40,39,38,0,98,0
2014,0,0,0,155,155,155,155,155,155,155,...,46,0,0,6,36,35,35,0,101,0
2015,0,0,0,154,154,154,154,154,154,154,...,50,1,1,8,33,33,33,1,102,0
2016,0,0,0,153,153,153,153,153,153,153,...,50,2,2,9,32,32,32,2,99,0
2017,0,0,0,154,154,154,154,154,154,154,...,53,2,2,11,32,32,32,2,100,0
2018,0,0,0,154,154,154,154,154,154,154,...,62,2,2,11,35,35,35,2,97,0
2019,0,0,0,0,0,0,0,0,0,0,...,64,3,3,8,34,34,34,3,92,0
2020,0,0,0,0,0,0,0,0,0,0,...,68,2,2,8,34,34,34,2,91,0
2021,0,0,0,0,0,0,0,0,0,0,...,71,2,2,10,37,37,37,2,94,0
2022,0,0,0,0,0,0,0,1,0,0,...,77,1,1,9,44,44,44,1,90,0
2023,0,0,0,0,0,3,3,3,3,3,...,84,3,3,16,76,75,75,3,110,0
2024,0,0,0,0,0,0,0,1,1,0,...,146,146,146,146,146,146,146,146,146,0

In [18]:
# Sauvegarder les versions propres

df.to_csv("../data/processed/final_clean.csv", index=False)