Charger fichier avec prédiction

In [1]:
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt

df_final = pd.read_csv("../data/processed/happiness_projections_2011_2030.csv")

In [2]:
df_final.columns

Index(['year', 'country_name', 'life_evaluation_3_year_average',
       'lower_whisker', 'upper_whisker', 'explained_by_log_gdp_per_capita',
       'explained_by_social_support', 'explained_by_healthy_life_expectancy',
       'explained_by_freedom_to_make_life_choices', 'explained_by_generosity',
       'explained_by_perceptions_of_corruption', 'dystopia_residual',
       'key_iso3_year', 'inflation_cpi', 'gdp_current_usd',
       'gdp_per_capita_current_usd', 'unemployment_rate_',
       'interest_rate_real', 'inflation_gdp_deflator', 'gdp_growth_annual',
       'current_account_balance_gdp', 'government_expense_of_gdp',
       'government_revenue_of_gdp', 'tax_revenue_of_gdp',
       'gross_national_income_usd', 'public_debt_of_gdp', 'country_code',
       'predicted_life_evaluation', 'pred_2024_x', 'real_2024_x', 'offset',
       'pred_2024_y', 'real_2024_y', 'pred_2024', 'real_2024'],
      dtype='str')

In [3]:
df_final.head(12)

,year,country_name,life_evaluation_3_year_average,lower_whisker,upper_whisker,explained_by_log_gdp_per_capita,explained_by_social_support,explained_by_healthy_life_expectancy,explained_by_freedom_to_make_life_choices,explained_by_generosity,...,public_debt_of_gdp,country_code,predicted_life_evaluation,pred_2024_x,real_2024_x,offset,pred_2024_y,real_2024_y,pred_2024,real_2024
0,2024,Afghanistan,1.364,1.301,1.427,0.649,0.000,0.155,0.0,0.075,...,NaN,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023,Afghanistan,1.721,1.667,1.775,0.628,0.000,0.242,0.0,0.091,...,NaN,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022,Afghanistan,1.859,1.795,1.923,0.645,0.000,0.087,0.0,0.093,...,NaN,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021,Afghanistan,2.404,2.339,2.469,0.758,0.000,0.289,0.0,0.089,...,NaN,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020,Afghanistan,2.523,2.449,2.596,0.370,0.000,0.126,0.0,0.122,...,NaN,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2019,Afghanistan,2.567,2.506,2.628,0.301,0.356,0.266,0.0,0.135,...,NaN,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2018,Afghanistan,3.203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2017,Afghanistan,3.632,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2016,Afghanistan,3.794,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2015,Afghanistan,3.360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2014,Afghanistan,3.575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2012,Afghanistan,4.040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
country = "United States"
df_country = df_final[df_final["country_name"] == country]

df_country = df_country.sort_values("year").reset_index(drop=True)
df_country["life_evaluation_3_year_average"] = (
    df_country["life_evaluation_3_year_average"].interpolate()
)

fig = px.line(
    df_country,
    x="year",
    y="life_evaluation_3_year_average",
    title=f"Évolution du bonheur – {country} (2014–2030)",
    markers=True
)

fig.update_traces(connectgaps=True)
fig.show()

In [13]:
country = "Belgium"
df_country = df_final[df_final["country_name"] == country].sort_values("year")

fig = px.line(
    df_country,
    x="year",
    y="life_evaluation_3_year_average",
    title=f"Évolution du bonheur – {country} (2011–2030)",
    markers=True
)

fig.update_traces(connectgaps=True)
fig.show()

In [6]:
df_country[df_country["year"] >= 2024][["year", "life_evaluation_3_year_average"]]

      year  life_evaluation_3_year_average
576   2024                        6.593000
2243  2025                        7.062643
2244  2026                        6.762136
2245  2027                        6.817711
2246  2028                        6.749588
2247  2029                        6.828708
2248  2030                        6.809154

# Top 10 - Happiness en 2030

In [14]:
df_2030 = df_final[df_final["year"] == 2030].copy()

In [15]:
top10 = df_2030.nlargest(10, "life_evaluation_3_year_average")

In [16]:
fig = px.bar(
    top10.sort_values("life_evaluation_3_year_average"),
    x="life_evaluation_3_year_average",
    y="country_name",
    orientation="h",
    title="Top 10 des pays les plus heureux en 2030",
    color="life_evaluation_3_year_average",
    color_continuous_scale="Blues"
)
fig.show()

# Flop 10

In [17]:
flop10 = df_2030.nsmallest(10, "life_evaluation_3_year_average")

In [18]:
fig = px.bar(
    flop10.sort_values("life_evaluation_3_year_average"),
    x="life_evaluation_3_year_average",
    y="country_name",
    orientation="h",
    title="Flop 10 des pays les moins heureux en 2030",
    color="life_evaluation_3_year_average",
    color_continuous_scale="Reds"
)
fig.show()

# Carte Mondiale

In [27]:
fig = px.choropleth(
    df_2030,
    locations="country_name",
    locationmode="country names",
    color="life_evaluation_3_year_average",
    color_continuous_scale="Viridis",
    title="Bonheur mondial en 2030",
)
fig.update_layout(
    width=1400,
    height=700,
    geo=dict(showframe=False, showcoastlines=False)
)


fig.show()

In [28]:
df_2030 = df_final[df_final["year"] == 2030].copy()

fig = px.choropleth(
    df_2030,
    locations="country_name",
    locationmode="country names",
    color="life_evaluation_3_year_average",
    hover_name="country_name",
    hover_data={
        "life_evaluation_3_year_average": True,
        "year": False
    },
    color_continuous_scale="RdYlGn",
    title="Bonheur mondial en 2030",
)

fig.update_layout(
    geo=dict(showframe=False, showcoastlines=False),
    coloraxis_colorbar=dict(
        title="Bonheur",
        ticks="outside"
    )
)
fig.update_layout(
    autosize=True,
    height=700,
    margin=dict(l=0, r=0, t=50, b=0)
)


fig.show()

# animation

In [30]:
df_final = df_final.sort_values("year")
df_final["year"] = df_final["year"].astype(int)

fig = px.choropleth(
    df_final,
    locations="country_name",
    locationmode="country names",
    color="life_evaluation_3_year_average",
    animation_frame="year",
    color_continuous_scale="RdYlGn",
    title="Évolution du bonheur mondial (2011–2030)",
)

fig.update_layout(
    autosize=True,
    height=750,
    margin=dict(l=0, r=0, t=50, b=0),
    geo=dict(showframe=False, showcoastlines=False)
)

fig.show()

# Courbe multi-pays

In [37]:
countries = [
    "Afghanistan",
    "Bolivia",
    "Botswana",
    "Bulgaria",
    "Costa Rica",
    "Finland",
    "United States",
    "China"
]

df_sel = df_final[df_final["country_name"].isin(countries)]

fig = px.line(
    df_sel,
    x="year",
    y="life_evaluation_3_year_average",
    color="country_name",
    markers=True,
    title="Évolution du bonheur (2011–2030) — 8 pays sélectionnés"
)

fig.update_traces(connectgaps=True)

fig.update_layout(
    autosize=True,
    height=650,
    margin=dict(l=0, r=0, t=50, b=0),
    legend_title_text="Pays"
)

fig.show()


### Lecture générale du graphique

Le modèle projette le niveau de bonheur en prolongeant les tendances historiques, en intégrant les indicateurs macro‑économiques et en appliquant un lissage temporel. Il ne prédit pas des événements politiques, mais extrapole les dynamiques observées dans les données réelles.

### Analyse rapide par pays (1 ligne chacun)

- **Afghanistan** : forte chute liée à la situation politique récente, suivie d’un léger rebond statistique dû à la stabilisation des indicateurs macro.  
- **Bolivia** : trajectoire globalement stable avec une légère tendance à la hausse, cohérente avec une croissance modérée et des indicateurs sociaux relativement constants.  
- **Botswana** : baisse progressive depuis 2014–2015, en ligne avec le ralentissement économique et les inégalités persistantes. (Chute du marché du diamant) 
- **Bulgaria** : amélioration régulière, portée par la croissance économique et l’intégration européenne.  
- **Costa Rica** : niveau élevé mais légèrement décroissant, reflétant des pressions économiques malgré un fort capital social.  
- **Finland** : stabilité à un niveau très élevé, cohérente avec ses performances sociales et institutionnelles.  
- **United States** : tendance légèrement descendante, influencée par les inégalités et les tensions sociales.  
- **China** : progression lente mais continue, portée par l’amélioration du niveau de vie malgré des défis sociaux.